base_configure: 
  server_name: node_server1
  logger_file: node_server1.log
  byte_order: 0
  addr_ip: 0.0.0.0
  addr_port: 40010
pack_handle:
  PACK_TYPE_CONNECT: cmd_connect
  PACK_TYPE_CREATE_CHANNEL: cmd_create_channel
  PACK_TYPE_DESTROY_CHANNEL: cmd_destroy_channel
  PACK_TYPE_MESSAGE_CHANNEL: cmd_message_channel
center_server:
  name: CenterServer
  addr_ip: 0.0.0.0
  addr_port: 40020
database_server:
  name: DatabaseServer
  addr_ip: 0.0.0.0
  addr_port: 40030