base_configure: 
  server_name: center_server
  logger_file: center_server.log
  byte_order: 0
  addr_ip: 0.0.0.0
  addr_port: 39999
pack_handle:
  PACK_TYPE_CREATE_CHANNEL: cmd_create_channel
  PACK_TYPE_DESTROY_CHANNEL: cmd_destroy_channel
  PACK_TYPE_MESSAGE_CHANNEL: cmd_message_channel
