base_configure: 
  server_name: run_server
  logger_file: logs/run_server.log
  byte_order: 0
  addr_ip: 0.0.0.0
  addr_port: 50562
pack_handle:
  PACK_TYPE_VERSION: cmd_version
db_server:
  name: DBServer
  addr_ip: 0.0.0.0
  addr_port: 50563