base_configure: 
  server_name: gate_server1
  logger_file: gate_server1.log
  byte_order: 0
  addr_ip: 0.0.0.0
  addr_port: 40000
pack_handle:
  PACK_TYPE_RECONNECT: cmd_reconnect
node_servers:
  - node_server:
      name: NodeServer1
      addr_ip: 0.0.0.0
      addr_port: 40010
  - node_server:
      name: NodeServer2
      addr_ip: 0.0.0.0
      addr_port: 40011
disable_route:
  - PACK_TYPE_CREATE_CHANNEL
  - PACK_TYPE_DESTROY_CHANNEL