base_configure: 
  server_name: gate_server2
  logger_file: gate_server2.log
  byte_order: 0
  addr_ip: 0.0.0.0
  addr_port: 40005
pack_handle:
  PACK_TYPE_RECONNECT: cmd_reconnect
node_servers:
  - node_server:
      name: NodeServer1
      addr_ip: 0.0.0.0
      addr_port: 40001
  - node_server:
      name: NodeServer2
      addr_ip: 0.0.0.0
      addr_port: 40002
disable_route:
  - PACK_TYPE_CREATE_CHANNEL
  - PACK_TYPE_DESTROY_CHANNEL