base_configure: 
  server_name: run_server
  logger_file: logs/run_server.log
  byte_order: 0
  addr_ip: 0.0.0.0
  addr_port: 50562
pack_handle:
  PACK_TYPE_LOGIN: login
  PACK_TYPE_INIT_PLAYER: init_player
  PACK_TYPE_CHAT_MSG: chat_msg
db_server:
  name: DBServer
  addr_ip: 0.0.0.0
  addr_port: 50563