base_configure: 
  server_name: gate_server
  logger_file: gate_server.log
  byte_order: 0
  addr_ip: 0.0.0.0
  addr_port: 40000
pack_handle: 
simple_server:
  name: SimpleServer
  addr_ip: 0.0.0.0
  addr_port: 40001
time_server:
  name: TimeServer
  addr_ip: 0.0.0.0
  addr_port: 40002