base_configure: 
  server_name: login_server
  logger_file: logs/login_server.log
  byte_order: 0
  addr_ip: 0.0.0.0
  addr_port: 50561
pack_handle:
  PACK_TYPE_VERSION: version
  PACK_TYPE_AUTHORIZE: authorize
  PACK_TYPE_REGIST: regist