boomman_configure:
  max_gold: 999999999
  max_diamonds: 999999999
  max_prestige: 999999999
mysql_configure:
  host: "10.10.1.121"
  port: 3306
  username: "root"
  password: "61Zentao@games_"
  database: "boomman"
redis_configure:
  - "10.10.1.121:6400"
  - "10.10.1.121:6401"
  - "10.10.1.121:6402"
redis_virtual_count: 5
log_name: logs/game.log
version: "0.0.1"
services:
  - server_class: DBServer
    configure_file: configure/db_configure/configure.yaml
  - server_class: LoginServer
    configure_file: configure/login_configure/configure.yaml
  - server_class: RunServer
    configure_file: configure/run_configure/configure.yaml
  - server_class: GateServer
    configure_file: configure/gate_configure/configure.yaml
enable_http:  true
