boomman_configure:
  max_gold: 999999999
  max_diamonds: 999999999
  max_prestige: 999999999
mysql_configure:
  host: "172.16.96.128"
  port: 3306
  username: "root"
  password: "123456"
  database: "boomman"
redis_configure:
  host: "172.16.96.128"
  port: 6379