base_configure: 
  server_name: gate_server
  logger_file: logs/gate_server.log
  byte_order: 0
  addr_ip: 0.0.0.0
  addr_port: 50560
pack_handle:
  PACK_TYPE_REGIST_SESSION: regiest_session
  PACK_TYPE_VERSION: version
login_server:
  name: LoginServer
  addr_ip: 0.0.0.0
  addr_port: 50561
run_server:
  name: RunServer
  addr_ip: 0.0.0.0
  addr_port: 50562